import {
  Shipment, Vehicle, Disruption, Route, Carrier, ColdChainAlert,
  Recommendation, Activity, NotificationItem
} from './types'

export const mockShipments: Shipment[] = [
  {
    id: 'SH1024',
    cargo: 'Electronics',
    value: 2400000,
    origin: 'Mumbai',
    destination: 'Frankfurt',
    currentLocation: 'Arabian Sea',
    carrier: 'Maersk Line',
    eta: 'Mar 18, 14:00',
    predictedDelay: 8.2,
    riskScore: 94,
    riskLevel: 'critical',
    status: 'at-risk',
    route: 'Mumbai → Frankfurt',
    color: 'red',
    temp: '—',
    disruption: 'Mumbai Port Strike',
    affectedByDisruptions: ['D001'],
    coldChainCapable: true,
  },
  {
    id: 'SH1021',
    cargo: 'Pharmaceuticals',
    value: 1800000,
    origin: 'Shenzhen',
    destination: 'Rotterdam',
    currentLocation: 'South China Sea',
    carrier: 'CMA CGM',
    eta: 'Mar 17, 09:30',
    predictedDelay: 2.1,
    riskScore: 31,
    riskLevel: 'low',
    status: 'in-transit',
    route: 'Shenzhen → Rotterdam',
    color: 'blue',
    temp: '4.2°C',
    coldChainCapable: true,
  },
  {
    id: 'SH1019',
    cargo: 'Automotive Parts',
    value: 950000,
    origin: 'Los Angeles',
    destination: 'Hamburg',
    currentLocation: 'Pacific Ocean',
    carrier: 'Hapag-Lloyd',
    eta: 'Mar 19, 16:20',
    predictedDelay: 1.2,
    riskScore: 22,
    riskLevel: 'low',
    status: 'in-transit',
    route: 'Los Angeles → Hamburg',
    color: 'blue',
    temp: '—',
  },
  {
    id: 'SH1016',
    cargo: 'Textiles',
    value: 580000,
    origin: 'Singapore',
    destination: 'Felixstowe',
    currentLocation: 'Felixstowe Port',
    carrier: 'Ocean Network Express',
    eta: 'Mar 15, 08:10',
    predictedDelay: 0,
    riskScore: 8,
    riskLevel: 'low',
    status: 'delivered',
    route: 'Singapore → Felixstowe',
    color: 'green',
    temp: '—',
  },
  {
    id: 'SH1013',
    cargo: 'Machinery',
    value: 3200000,
    origin: 'Busan',
    destination: 'Long Beach',
    currentLocation: 'Pacific Ocean',
    carrier: 'MSC',
    eta: 'Mar 20, 11:45',
    predictedDelay: 4.8,
    riskScore: 68,
    riskLevel: 'high',
    status: 'delayed',
    route: 'Busan → Long Beach',
    color: 'amber',
    temp: '—',
    affectedByDisruptions: ['D003'],
  },
  {
    id: 'SH1011',
    cargo: 'Consumer Electronics',
    value: 1600000,
    origin: 'Hong Kong',
    destination: 'Singapore',
    currentLocation: 'Hong Kong Port',
    carrier: 'Evergreen Marine',
    eta: 'Mar 17, 14:30',
    predictedDelay: 0.5,
    riskScore: 28,
    riskLevel: 'low',
    status: 'in-transit',
    route: 'Hong Kong → Singapore',
    color: 'blue',
    temp: '—',
  },
  {
    id: 'SH1010',
    cargo: 'Food & Beverage',
    value: 420000,
    origin: 'Bangkok',
    destination: 'Mumbai',
    currentLocation: 'Indian Ocean',
    carrier: 'Maersk Line',
    eta: 'Mar 18, 22:00',
    predictedDelay: 7.2,
    riskScore: 82,
    riskLevel: 'high',
    status: 'at-risk',
    route: 'Bangkok → Mumbai',
    color: 'red',
    temp: '6.1°C',
    disruption: 'Heavy Rainfall',
    affectedByDisruptions: ['D002'],
    coldChainCapable: true,
  },
  {
    id: 'SH1009',
    cargo: 'Chemicals',
    value: 2100000,
    origin: 'Rotterdam',
    destination: 'Singapore',
    currentLocation: 'Suez Canal',
    carrier: 'CMA CGM',
    eta: 'Mar 25, 10:15',
    predictedDelay: 3.4,
    riskScore: 42,
    riskLevel: 'medium',
    status: 'in-transit',
    route: 'Rotterdam → Singapore',
    color: 'amber',
    temp: '—',
    affectedByDisruptions: ['D004'],
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: 'VH-021',
    type: 'Refrigerated truck',
    location: 'Mundra Hub',
    capacity: '14 tons',
    status: 'available',
    utilization: 12,
    coldChainCapable: true,
    reliability: 96,
  },
  {
    id: 'VH-208',
    type: 'Volvo FH16',
    location: 'Rotterdam',
    capacity: '22 tons',
    status: 'maintenance',
    utilization: 0,
    coldChainCapable: false,
    reliability: 92,
  },
  {
    id: 'VH-114',
    type: 'Dry van',
    location: 'Mumbai',
    capacity: '18 tons',
    status: 'assigned',
    utilization: 82,
    coldChainCapable: false,
    reliability: 88,
    assignment: 'SH1024',
  },
  {
    id: 'VH-087',
    type: 'Reefer truck',
    location: 'Pune',
    capacity: '12 tons',
    status: 'available',
    utilization: 28,
    coldChainCapable: true,
    reliability: 94,
  },
  {
    id: 'VH-156',
    type: 'Flatbed',
    location: 'Shanghai',
    capacity: '28 tons',
    status: 'assigned',
    utilization: 71,
    coldChainCapable: false,
    reliability: 90,
    assignment: 'SH1013',
  },
  {
    id: 'VH-042',
    type: 'Reefer truck',
    location: 'Bangkok',
    capacity: '11 tons',
    status: 'assigned',
    utilization: 65,
    coldChainCapable: true,
    reliability: 93,
    assignment: 'SH1010',
  },
]

export const mockDisruptions: Disruption[] = [
  {
    id: 'D001',
    name: 'Mumbai Port Strike',
    type: 'Labor action',
    location: 'Mumbai',
    severity: 'critical',
    status: 'active',
    startTime: 'Mar 16, 08:00',
    expectedDuration: '36 hours',
    affectedShipmentIds: ['SH1024', 'SH1006', 'SH1007', 'SH1008', 'SH1009', 'SH1010'],
    affectedRouteIds: ['R001', 'R002', 'R003'],
    affectedCarriers: ['Maersk Line', 'Ocean Network Express', 'Evergreen Marine'],
    estimatedDelay: 7.2,
    confidence: 94,
  },
  {
    id: 'D002',
    name: 'Heavy Rainfall',
    type: 'Weather',
    location: 'Surat',
    severity: 'high',
    status: 'active',
    startTime: 'Mar 16, 12:00',
    expectedDuration: '18 hours',
    affectedShipmentIds: ['SH1010', 'SH1014', 'SH1015'],
    affectedRouteIds: ['R004', 'R005'],
    affectedCarriers: ['Maersk Line', 'CMA CGM'],
    estimatedDelay: 4.1,
    confidence: 87,
  },
  {
    id: 'D003',
    name: 'Road Closure (NH48)',
    type: 'Infrastructure',
    location: 'Bangalore',
    severity: 'medium',
    status: 'monitoring',
    startTime: 'Mar 15, 20:00',
    expectedDuration: '24 hours',
    affectedShipmentIds: ['SH1013', 'SH1017', 'SH1018'],
    affectedRouteIds: ['R006'],
    affectedCarriers: ['MSC'],
    estimatedDelay: 3.2,
    confidence: 76,
  },
  {
    id: 'D004',
    name: 'Port Congestion',
    type: 'Capacity constraint',
    location: 'Singapore',
    severity: 'high',
    status: 'active',
    startTime: 'Mar 14, 06:00',
    expectedDuration: '72 hours',
    affectedShipmentIds: ['SH1009', 'SH1012', 'SH1020', 'SH1022'],
    affectedRouteIds: ['R007', 'R008'],
    affectedCarriers: ['CMA CGM', 'Hapag-Lloyd', 'MSC'],
    estimatedDelay: 5.8,
    confidence: 91,
  },
]

export const mockRoutes: Route[] = [
  {
    id: 'R-ALT-1',
    origin: 'Mumbai',
    destination: 'Frankfurt',
    predictedDelay: 2.1,
    cost: 48000,
    riskLevel: 'low',
    recommended: true,
  },
  {
    id: 'R-ALT-2',
    origin: 'Mumbai',
    destination: 'Frankfurt',
    predictedDelay: 4.2,
    cost: 52000,
    riskLevel: 'medium',
  },
  {
    id: 'R-ALT-3',
    origin: 'Mumbai',
    destination: 'Frankfurt',
    predictedDelay: 6.8,
    cost: 45000,
    riskLevel: 'high',
  },
]

export const mockCarriers: Carrier[] = [
  {
    id: 'C-MAER',
    name: 'Maersk Line',
    reliability: 94,
    capacity: 'available',
    costDelta: 0,
    predictedDelay: 8.2,
    riskLevel: 'critical',
  },
  {
    id: 'C-CMACGM',
    name: 'CMA CGM',
    reliability: 91,
    capacity: 'available',
    costDelta: 4,
    predictedDelay: 2.1,
    riskLevel: 'low',
  },
  {
    id: 'C-HAPAG',
    name: 'Hapag-Lloyd',
    reliability: 87,
    capacity: 'limited',
    costDelta: -2,
    predictedDelay: 4.3,
    riskLevel: 'medium',
  },
]

export const mockColdChainAlerts: ColdChainAlert[] = [
  {
    id: 'CCA-001',
    shipmentId: 'SH1024',
    trackerId: 'TR-41',
    currentTemp: 9.7,
    safeRangeMin: 2,
    safeRangeMax: 8,
    excursionDuration: 18,
    severity: 'critical',
    location: 'Arabian Sea',
    status: 'active',
  },
  {
    id: 'CCA-002',
    shipmentId: 'SH1021',
    trackerId: 'TR-38',
    currentTemp: 4.2,
    safeRangeMin: 2,
    safeRangeMax: 8,
    excursionDuration: 0,
    severity: 'medium',
    location: 'South China Sea',
    status: 'active',
  },
]

export const mockRecommendations: Recommendation[] = [
  {
    id: 'REC-001',
    type: 'reroute',
    title: 'Reroute SH1024 via Mundra',
    description: 'Current route is exposed to Mumbai Port Strike. Mundra has available capacity and lower disruption exposure.',
    shipmentId: 'SH1024',
    confidence: 94,
    expectedBenefit: 'Expected delay reduction: 5.2h',
    status: 'pending',
    impact: 'critical',
  },
  {
    id: 'REC-002',
    type: 'redeploy',
    title: 'Redeploy VH-021 to SH1024',
    description: 'Refrigerated truck is 12 km away with 14-ton capacity and is available now.',
    shipmentId: 'SH1024',
    vehicleId: 'VH-021',
    confidence: 94,
    expectedBenefit: 'Protects cold-chain cargo',
    status: 'pending',
    impact: 'high',
  },
  {
    id: 'REC-003',
    type: 'switch-carrier',
    title: 'Switch carrier for SH1013',
    description: 'MSC is delayed on Busan-Long Beach route. CMA CGM alternative offers 3.2h faster transit.',
    shipmentId: 'SH1013',
    carrierId: 'C-CMACGM',
    confidence: 87,
    expectedBenefit: '3.2h faster delivery',
    status: 'pending',
    impact: 'high',
  },
  {
    id: 'REC-004',
    type: 'monitor',
    title: 'Monitor SH1010 cold chain',
    description: 'Food shipment is experiencing temperature excursions. VH-042 is maintaining safe range.',
    shipmentId: 'SH1010',
    confidence: 92,
    expectedBenefit: 'Prevent spoilage',
    status: 'pending',
    impact: 'critical',
  },
  {
    id: 'REC-005',
    type: 'redeploy',
    title: 'Deploy VH-087 to Bangalore',
    description: 'Idle reefer truck can support rerouted pharmaceutical shipments from NH48 closure.',
    vehicleId: 'VH-087',
    confidence: 81,
    expectedBenefit: 'Optimize regional capacity',
    status: 'pending',
    impact: 'medium',
  },
]

export const mockActivities: Activity[] = [
  {
    id: 'ACT-001',
    type: 'cold-chain',
    title: 'Temperature excursion detected',
    description: 'SH1024 · TR-41 reached 9.7°C',
    timestamp: 'Mar 16, 14:22',
    severity: 'critical',
    relatedId: 'SH1024',
  },
  {
    id: 'ACT-002',
    type: 'disruption',
    title: 'Disruption escalated',
    description: 'Mumbai Port Strike now Critical',
    timestamp: 'Mar 16, 13:45',
    severity: 'critical',
    relatedId: 'D001',
  },
  {
    id: 'ACT-003',
    type: 'shipment',
    title: 'Shipment delivered',
    description: 'SH1016 · Textiles · Singapore → Felixstowe',
    timestamp: 'Mar 15, 08:32',
    relatedId: 'SH1016',
  },
  {
    id: 'ACT-004',
    type: 'recommendation',
    title: 'Carrier score updated',
    description: 'Maersk Line reliability decreased to 94%',
    timestamp: 'Mar 15, 12:15',
  },
  {
    id: 'ACT-005',
    type: 'shipment',
    title: 'Reroute applied',
    description: 'SH1024 · New route via Mundra',
    timestamp: 'Mar 15, 11:08',
    relatedId: 'SH1024',
  },
]

export const mockNotifications: NotificationItem[] = [
  {
    id: 'NOT-001',
    type: 'critical',
    title: 'Critical shipment at risk',
    description: 'SH1024 risk score: 94/100',
    timestamp: 'Mar 16, 14:25',
    read: false,
    actionId: 'SH1024',
  },
  {
    id: 'NOT-002',
    type: 'disruption',
    title: 'New disruption: Mumbai Port Strike',
    description: 'Affects 6 shipments across 4 routes',
    timestamp: 'Mar 16, 14:12',
    read: false,
    actionId: 'D001',
  },
  {
    id: 'NOT-003',
    type: 'cold-chain',
    title: 'Cold chain alert',
    description: 'SH1024 · Temperature excursion 18 min',
    timestamp: 'Mar 16, 14:22',
    read: false,
    actionId: 'SH1024',
  },
  {
    id: 'NOT-004',
    type: 'recommendation',
    title: 'Recommendation available',
    description: '5 actions to reduce network risk',
    timestamp: 'Mar 16, 14:08',
    read: false,
    actionId: 'REC-001',
  },
]

export const temperatureData = [
  { t: '08:00', v: 3.8 },
  { t: '10:00', v: 4.1 },
  { t: '12:00', v: 4.0 },
  { t: '14:00', v: 5.4 },
  { t: '16:00', v: 7.9 },
  { t: '18:00', v: 9.7 },
  { t: '20:00', v: 8.4 },
  { t: '22:00', v: 6.1 },
]

export const utilizationData = [
  { name: 'In transit', value: 64, color: '#4f8cff' },
  { name: 'Available', value: 22, color: '#38c58a' },
  { name: 'Maintenance', value: 14, color: '#f2b84b' },
]
